server:
  port: 9296

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yogendramashete/config-server
          clone-on-start: true
        default-label: main